version: '3'

services:
   db:
    image: mysql:5.7
    volumes:
       - /data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: hackernews
    ports:
       - "3306:3306"
